"use client";

import { motion } from "framer-motion";
import {
  Flame, Droplet, Footprints, Dumbbell, Apple, TrendingDown, Search,
  Star, Check, ChevronDown, Menu, X, ShieldCheck, Sparkles, BarChart3
} from "lucide-react";
import { GlassCard } from "@/components/ui/Card";
import { useState } from "react";

const features = [
  {
    icon: Apple,
    title: "Smart Food Tracking",
    description: "Log meals in seconds with our massive database, barcode scanner, and AI meal suggestions.",
    color: "text-emerald-500 bg-emerald-500/10"
  },
  {
    icon: Dumbbell,
    title: "Custom Workouts",
    description: "Build routines, track sets, reps, and weight. Get rest timers and progress analytics.",
    color: "text-purple-500 bg-purple-500/10"
  },
  {
    icon: BarChart3,
    title: "Advanced Analytics",
    description: "Beautiful charts for weight, macros, and body measurements. Visualize your journey.",
    color: "text-blue-500 bg-blue-500/10"
  },
  {
    icon: Sparkles,
    title: "AI Nutrition Coach",
    description: "Get daily feedback, macro optimizations, and grocery lists generated by AI.",
    color: "text-amber-500 bg-amber-500/10"
  }
];

const stats = [
  { value: "10M+", label: "Active Users" },
  { value: "500M+", label: "Meals Logged" },
  { value: "99.9%", label: "Uptime" },
  { value: "4.9★", label: "App Store Rating" }
];

const testimonials = [
  {
    quote: "ApexFuel completely changed how I view nutrition. The UI is so clean, it actually makes tracking macros enjoyable.",
    name: "Sarah Chen",
    role: "Marathon Runner"
  },
  {
    quote: "The analytics dashboard is unmatched. I finally have a clear picture of my progress and what I need to adjust.",
    name: "Marcus Johnson",
    role: "Strength Coach"
  },
  {
    quote: "As a busy professional, the AI meal suggestions save me hours every week. It's like having a personal dietitian.",
    name: "Emily Davis",
    role: "Software Engineer"
  }
];

const pricingTiers = [
  {
    name: "Starter",
    price: "Free",
    description: "Perfect for getting started on your fitness journey.",
    features: ["Daily Calorie Tracking", "Basic Food Database", "Workout Logger", "7-Day Analytics"],
    cta: "Get Started",
    highlighted: false
  },
  {
    name: "Pro",
    price: "$9.99",
    description: "Advanced tools for serious athletes and enthusiasts.",
    features: ["Everything in Starter", "AI Nutrition Coach", "Barcode Scanner", "Custom Recipes", "Advanced Analytics", "Priority Support"],
    cta: "Start 14-Day Trial",
    highlighted: true
  },
  {
    name: "Elite",
    price: "$19.99",
    description: "The ultimate experience with premium integrations.",
    features: ["Everything in Pro", "Wearable Sync", "Unlimited AI Reports", "Meal Planning", "Family Sharing (up to 5)"],
    cta: "Contact Sales",
    highlighted: false
  }
];

const faqs = [
  {
    q: "Is my dietary data secure with ApexFuel?",
    a: "Absolutely. We use enterprise-grade encryption for all data in transit and at rest. Your health data is never sold to third parties."
  },
  {
    q: "Can I use ApexFuel without a premium subscription?",
    a: "Yes! Our Starter tier is free forever and includes core tracking features. You can upgrade anytime to unlock AI tools and advanced analytics."
  },
  {
    q: "Does it integrate with Apple Health or Google Fit?",
    a: "Yes, our Elite tier supports seamless integration with Apple Health, Google Fit, Garmin, and Fitbit to automatically sync steps and workouts."
  }
];

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-background text-foreground overflow-x-hidden">
      <Navbar />
      <HeroSection />
      <StatsSection />
      <DashboardPreviewSection />
      <FeaturesSection />
      <FoodTrackingPreviewSection />
      <AnalyticsPreviewSection />
      <TestimonialsSection />
      <PricingSection />
      <FaqSection />
      <Footer />
    </main>
  );
}

function Navbar() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <nav className="fixed top-0 left-0 right-0 z-50 px-4 md:px-8 py-4">
      <div className="max-w-7xl mx-auto flex items-center justify-between p-3 rounded-2xl bg-card/60 backdrop-blur-xl border border-border/50 shadow-lg">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg premium-gradient flex items-center justify-center">
            <Flame className="w-5 h-5 text-white" />
          </div>
          <span className="text-lg font-bold tracking-tight">ApexFuel</span>
        </div>
        
        <div className="hidden md:flex items-center gap-8">
          <a href="#features" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Features</a>
          <a href="#testimonials" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Reviews</a>
          <a href="#pricing" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Pricing</a>
          <a href="#faq" className="text-sm text-muted-foreground hover:text-foreground transition-colors">FAQ</a>
        </div>

        <div className="hidden md:flex items-center gap-3">
          <button className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">Sign In</button>
          <button className="px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-xl hover:opacity-90 transition-opacity">
            Get Started
          </button>
        </div>

        <button className="md:hidden p-2" onClick={() => setIsOpen(!isOpen)}>
          {isOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
        </button>
      </div>
      
      {isOpen && (
        <motion.div 
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="md:hidden mt-2 p-4 rounded-2xl bg-card border border-border flex flex-col gap-4"
        >
          <a href="#features" className="text-muted-foreground hover:text-foreground">Features</a>
          <a href="#testimonials" className="text-muted-foreground hover:text-foreground">Reviews</a>
          <a href="#pricing" className="text-muted-foreground hover:text-foreground">Pricing</a>
          <a href="#faq" className="text-muted-foreground hover:text-foreground">FAQ</a>
          <button className="w-full py-2 bg-primary text-primary-foreground rounded-xl font-medium">Get Started</button>
        </motion.div>
      )}
    </nav>
  );
}

function HeroSection() {
  return (
    <section className="relative pt-40 pb-20 md:pt-52 md:pb-32 px-4 md:px-8 overflow-hidden">
      {/* Background Glows */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-[120px] -z-10" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-500/20 rounded-full blur-[120px] -z-10" />

      <div className="max-w-5xl mx-auto text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="inline-flex items-center gap-2 px-4 py-1.5 mb-6 rounded-full border border-border bg-card/50 backdrop-blur-sm"
        >
          <Sparkles className="w-4 h-4 text-primary" />
          <span className="text-sm font-medium">Introducing AI Nutrition Coach</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight mb-6 bg-gradient-to-b from-foreground to-foreground/60 bg-clip-text text-transparent"
        >
          Fuel your body.<br />Track your progress.
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10"
        >
          The ultimate premium fitness platform. Track macros, log workouts, and analyze progress with Apple-level design and enterprise-grade architecture.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <button className="w-full sm:w-auto px-8 py-3.5 premium-gradient text-white font-semibold rounded-2xl hover:opacity-90 transition-opacity flex items-center gap-2">
            Start Tracking Free <Apple className="w-4 h-4" />
          </button>
          <button className="w-full sm:w-auto px-8 py-3.5 bg-card border border-border text-foreground font-semibold rounded-2xl hover:bg-muted transition-colors">
            View Demo
          </button>
        </motion.div>
      </div>
    </section>
  );
}

function StatsSection() {
  return (
    <section className="py-12 px-4 md:px-8 border-y border-border/50 bg-card/30 backdrop-blur-sm">
      <div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">
        {stats.map((stat, i) => (
          <motion.div 
            key={i}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: i * 0.1 }}
            className="text-center"
          >
            <div className="text-3xl md:text-5xl font-bold bg-gradient-to-b from-foreground to-foreground/60 bg-clip-text text-transparent">{stat.value}</div>
            <div className="text-sm text-muted-foreground mt-2">{stat.label}</div>
          </motion.div>
        ))}
      </div>
    </section>
  );
}

function DashboardPreviewSection() {
  return (
    <section className="py-24 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
        >
          <GlassCard className="p-2 md:p-4 shadow-2xl">
            <div className="rounded-2xl bg-background overflow-hidden">
              {/* Mock Dashboard UI */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-4 md:p-8">
                <div className="md:col-span-1 flex flex-col items-center justify-center p-8 rounded-xl bg-card border border-border/50">
                  <div className="relative w-40 h-40 flex items-center justify-center">
                    <svg className="absolute inset-0 w-full h-full -rotate-90" viewBox="0 0 100 100">
                      <circle cx="50" cy="50" r="45" fill="none" stroke="rgb(var(--muted))" strokeWidth="8" />
                      <motion.circle 
                        cx="50" cy="50" r="45" fill="none" stroke="rgb(var(--primary))" strokeWidth="8" 
                        strokeLinecap="round"
                        strokeDasharray="282.7"
                        initial={{ strokeDashoffset: 282.7 }}
                        whileInView={{ strokeDashoffset: 282.7 - (282.7 * 0.73) }}
                        viewport={{ once: true }}
                        transition={{ duration: 1.5, ease: "easeInOut", delay: 0.5 }}
                      />
                    </svg>
                    <div className="text-center">
                      <p className="text-4xl font-bold">540</p>
                      <p className="text-xs text-muted-foreground uppercase">Remaining</p>
                    </div>
                  </div>
                  <div className="mt-4 text-center text-sm text-muted-foreground">
                    <p>1460 Eaten • 200 Burned</p>
                  </div>
                </div>
                <div className="md:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-6 rounded-xl bg-card border border-border/50">
                    <h3 className="text-sm font-medium mb-4 text-muted-foreground">Macronutrients</h3>
                    <div className="space-y-4">
                      <div>
                        <div className="flex justify-between text-xs mb-1"><span>Protein</span><span>120/150g</span></div>
                        <div className="w-full bg-muted rounded-full h-2"><div className="bg-blue-500 h-full rounded-full w-[80%]"></div></div>
                      </div>
                      <div>
                        <div className="flex justify-between text-xs mb-1"><span>Carbs</span><span>180/200g</span></div>
                        <div className="w-full bg-muted rounded-full h-2"><div className="bg-amber-500 h-full rounded-full w-[90%]"></div></div>
                      </div>
                      <div>
                        <div className="flex justify-between text-xs mb-1"><span>Fat</span><span>45/65g</span></div>
                        <div className="w-full bg-muted rounded-full h-2"><div className="bg-purple-500 h-full rounded-full w-[70%]"></div></div>
                      </div>
                    </div>
                  </div>
                  <div className="p-6 rounded-xl bg-card border border-border/50 flex flex-col justify-between">
                    <h3 className="text-sm font-medium mb-2 text-muted-foreground">Water & Steps</h3>
                    <div className="flex items-center gap-2 mb-4">
                      <Droplet className="w-5 h-5 text-blue-500" />
                      <span className="text-2xl font-bold">1.5L</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Footprints className="w-5 h-5 text-amber-500" />
                      <span className="text-2xl font-bold">8,420</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </GlassCard>
        </motion.div>
      </div>
    </section>
  );
}

function FeaturesSection() {
  return (
    <section id="features" className="py-24 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">Everything you need to succeed</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">A comprehensive suite of tools designed to make health tracking effortless and insightful.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
            >
              <GlassCard className="h-full hover:scale-[1.02] transition-transform">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${feature.color}`}>
                  <feature.icon className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground">{feature.description}</p>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FoodTrackingPreviewSection() {
  return (
    <section className="py-24 px-4 md:px-8 bg-card/30 border-y border-border/50">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-6">Log meals in seconds</h2>
          <p className="text-muted-foreground mb-8 text-lg">
            Stop wasting time searching for foods. Our massive verified database and barcode scanner make logging frictionless.
          </p>
          <ul className="space-y-4">
            {["Barcode scanner integration", "Millions of verified foods", "Save custom meals and recipes", "AI meal suggestions"].map((item, i) => (
              <li key={i} className="flex items-center gap-3">
                <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center">
                  <Check className="w-4 h-4 text-primary" />
                </div>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </motion.div>
        
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="relative"
        >
          <GlassCard className="p-6 shadow-2xl">
            <div className="flex items-center gap-2 mb-4 p-3 rounded-xl bg-muted/50">
              <Search className="w-5 h-5 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Search for food...</span>
            </div>
            <div className="space-y-3">
              {[
                { name: "Chicken Breast", cal: 165, p: 31, c: 0, f: 3.6 },
                { name: "Avocado", cal: 160, p: 2, c: 9, f: 15 },
                { name: "Brown Rice", cal: 216, p: 5, c: 45, f: 1.8 }
              ].map((food, i) => (
                <div key={i} className="p-4 rounded-xl border border-border/50 hover:bg-muted/30 transition-colors cursor-pointer">
                  <div className="flex justify-between items-center">
                    <h4 className="font-medium">{food.name}</h4>
                    <span className="text-xs text-muted-foreground">{food.cal} cal</span>
                  </div>
                  <div className="text-xs text-muted-foreground mt-1">P: {food.p}g • C: {food.c}g • F: {food.f}g</div>
                </div>
              ))}
            </div>
          </GlassCard>
        </motion.div>
      </div>
    </section>
  );
}

function AnalyticsPreviewSection() {
  return (
    <section className="py-24 px-4 md:px-8">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="relative order-2 md:order-1"
        >
          <GlassCard className="p-6 shadow-2xl">
            <h4 className="text-sm text-muted-foreground mb-4">Weight Progress</h4>
            <div className="h-48 flex items-end justify-between gap-2">
              {[80, 79.5, 79, 78.2, 78, 77.5, 76.8].map((h, i) => (
                <div key={i} className="flex-1 flex flex-col items-center gap-2">
                  <motion.div 
                    initial={{ height: 0 }}
                    whileInView={{ height: `${h * 3}px` }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.8, delay: i * 0.1 }}
                    className="w-full bg-gradient-to-t from-primary to-primary/50 rounded-t-lg"
                  />
                  <span className="text-xs text-muted-foreground">D{i+1}</span>
                </div>
              ))}
            </div>
          </GlassCard>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, x: 20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="order-1 md:order-2"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-6">Insights that drive results</h2>
          <p className="text-muted-foreground mb-8 text-lg">
            Beautiful, interactive charts visualize your weight, macros, and body measurements over time. Identify trends and stay motivated.
          </p>
          <ul className="space-y-4">
            {["Interactive time-series charts", "Body measurement tracking", "Calorie and macro breakdowns", "Custom date ranges"].map((item, i) => (
              <li key={i} className="flex items-center gap-3">
                <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center">
                  <TrendingDown className="w-4 h-4 text-primary" />
                </div>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </motion.div>
      </div>
    </section>
  );
}

function TestimonialsSection() {
  return (
    <section id="testimonials" className="py-24 px-4 md:px-8 bg-card/30 border-y border-border/50">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">Loved by athletes</h2>
          <p className="text-muted-foreground">Join thousands who have transformed their fitness journey.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((t, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
            >
              <GlassCard className="h-full flex flex-col">
                <div className="flex gap-1 mb-4">
                  {[1,2,3,4,5].map(s => <Star key={s} className="w-4 h-4 fill-amber-400 text-amber-400" />)}
                </div>
                <p className="text-muted-foreground mb-6 flex-1">"{t.quote}"</p>
                <div>
                  <p className="font-semibold">{t.name}</p>
                  <p className="text-sm text-muted-foreground">{t.role}</p>
                </div>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function PricingSection() {
  return (
    <section id="pricing" className="py-24 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">Simple, transparent pricing</h2>
          <p className="text-muted-foreground">Start free. Upgrade when you're ready.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
          {pricingTiers.map((tier, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              className={`relative ${tier.highlighted ? 'scale-105 z-10' : ''}`}
            >
              <GlassCard className={`h-full flex flex-col ${tier.highlighted ? 'border-primary/50 border-2' : ''}`}>
                {tier.highlighted && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 bg-primary text-primary-foreground text-xs font-medium rounded-full">
                    Most Popular
                  </div>
                )}
                <h3 className="text-xl font-semibold mb-2">{tier.name}</h3>
                <p className="text-sm text-muted-foreground mb-4">{tier.description}</p>
                <div className="mb-6">
                  <span className="text-4xl font-bold">{tier.price}</span>
                  {tier.price !== "Free" && <span className="text-muted-foreground">/mo</span>}
                </div>
                <ul className="space-y-3 mb-8 flex-1">
                  {tier.features.map((f, i) => (
                    <li key={i} className="flex items-center gap-2 text-sm">
                      <Check className="w-4 h-4 text-primary" /> {f}
                    </li>
                  ))}
                </ul>
                <button className={`w-full py-3 rounded-xl font-medium transition-colors ${tier.highlighted ? 'premium-gradient text-white' : 'bg-muted hover:bg-muted/80'}`}>
                  {tier.cta}
                </button>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FaqSection() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <section id="faq" className="py-24 px-4 md:px-8 bg-card/30 border-y border-border/50">
      <div className="max-w-3xl mx-auto">
        <h2 className="text-4xl md:text-5xl font-bold mb-12 text-center">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqs.map((faq, i) => (
            <div key={i} className="border-b border-border pb-4">
              <button 
                onClick={() => setOpen(open === i ? null : i)}
                className="w-full flex justify-between items-center text-left py-2"
              >
                <span className="font-medium text-lg">{faq.q}</span>
                <ChevronDown className={`w-5 h-5 transition-transform ${open === i ? 'rotate-180' : ''}`} />
              </button>
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: open === i ? 'auto' : 0, opacity: open === i ? 1 : 0 }}
                transition={{ duration: 0.3 }}
                className="overflow-hidden"
              >
                <p className="text-muted-foreground pt-2">{faq.a}</p>
              </motion.div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="py-12 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg premium-gradient flex items-center justify-center">
              <Flame className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-bold tracking-tight">ApexFuel</span>
          </div>
          <div className="flex gap-6 text-sm text-muted-foreground">
            <a href="#" className="hover:text-foreground transition-colors">Privacy</a>
            <a href="#" className="hover:text-foreground transition-colors">Terms</a>
            <a href="#" className="hover:text-foreground transition-colors">Contact</a>
          </div>
          <div className="text-sm text-muted-foreground">
            © 2024 ApexFuel. All rights reserved.
          </div>
        </div>
      </div>
    </footer>
  );
}
